### ISSUE TITLE
5v power supply

### ISSUE THREAD

**Issue by itineric** [Serjeo722/QuantisUSB#1]
Hi,

Can you explain me how to get 5v to the USB ? What do you mean by "Cur here (USB pin 1)" ?

Regards,

Eric

**Comment by mcfly722** [comment]
By default **DuinoFun UHS mini v2.0 (Aug. 16, 2014)** requires 3.3 volts to work. If you will connect some USB device which is requires 3.3 volts (f.e. usb token) it would work fine, but if you connect another one which is requires 5 volts (f.e. Quantis Random Number Generator), it would not be able to provide this voltage.
Solution is to use third party USB hub which provide this 5 volts voltage for QTRNG, or cut circuit and power up this shield by 5 volt source.

Screen how to cut it you can find here: http://okiraku-camera.tokyo/blog/?p=8193
